// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 CAB Ingénierie / Christophe ABOULICAM
package initcmd

const dockerComposeTemplate = `# STOA Gateway — generated by stoactl init
# Usage: docker compose up -d
services:
  gateway:
    image: ghcr.io/stoa-platform/gateway:latest
    ports:
      - "{{.Port}}:8080"
    environment:
      - STOA_MODE=edge-mcp
      - STOA_LOG_LEVEL=info
      - STOA_ADMIN_TOKEN=dev-token
    volumes:
      - ./stoa.yaml:/etc/stoa/stoa.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  echo:
    image: nginx:alpine
    volumes:
      - ./echo-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "8888"
`

const stoaConfigTemplate = `# STOA Configuration — generated by stoactl init
# Docs: https://docs.gostoa.dev/docs/reference/config
apiVersion: stoa.io/v1
kind: GatewayConfig
metadata:
  name: {{.ProjectName}}
spec:
  mode: edge-mcp
  port: 8080
  admin:
    enabled: true
  logging:
    level: info
    format: json
`
