// SPDX-License-Identifier: Apache-2.0
// Copyright 2024-2026 CAB Ingénierie / Christophe ABOULICAM
package initcmd

const dockerComposeTemplate = `# STOA Gateway — generated by stoactl init
# Usage: docker compose up -d
services:
  gateway:
    image: ghcr.io/stoa-platform/gateway:latest
    ports:
      - "{{.Port}}:8080"
    environment:
      - STOA_MODE=edge-mcp
      - STOA_LOG_LEVEL=info
      - STOA_ADMIN_TOKEN=dev-token
    volumes:
      - ./stoa.yaml:/etc/stoa/stoa.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  echo:
    image: nginx:alpine
    volumes:
      - ./echo-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    expose:
      - "8888"
`

const stoaConfigTemplate = `# STOA Configuration — generated by stoactl init
# Docs: https://docs.gostoa.dev/docs/reference/config
apiVersion: stoa.io/v1
kind: GatewayConfig
metadata:
  name: {{.ProjectName}}
spec:
  mode: edge-mcp
  port: 8080
  admin:
    enabled: true
  logging:
    level: info
    format: json
`

const echoNginxTemplate = `# Echo backend — returns static JSON for testing
# Generated by stoactl init
server {
    listen 8888;
    location / {
        default_type application/json;
        return 200 '{"message":"hello from echo","service":"{{.ProjectName}}"}';
    }
    location /health {
        default_type application/json;
        return 200 '{"status":"ok"}';
    }
}
`

const exampleAPITemplate = `# Example OpenAPI spec — use with stoactl bridge
# Usage: stoactl bridge example-api.yaml --namespace default --output ./tools/
openapi: "3.0.0"
info:
  title: {{.ProjectName}} API
  version: "1.0.0"
  description: Example API for MCP bridge demonstration
servers:
  - url: http://echo:8888
    description: Local echo backend (Docker network)
paths:
  /items:
    get:
      operationId: listItems
      summary: List all items
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            maximum: 100
            default: 20
      responses:
        "200":
          description: List of items
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Item"
    post:
      operationId: createItem
      summary: Create a new item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
              required:
                - name
      responses:
        "201":
          description: Item created
  /items/{itemId}:
    get:
      operationId: getItem
      summary: Get an item by ID
      parameters:
        - name: itemId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Item details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        createdAt:
          type: string
          format: date-time
`

const readmeTemplate = `# {{.ProjectName}}

> Generated by ` + "`stoactl init`" + ` — STOA Platform CLI

## Quick Start (5 minutes)

### 1. Start the gateway

` + "```bash" + `
docker compose up -d
` + "```" + `

### 2. Verify it's running

` + "```bash" + `
stoactl doctor
` + "```" + `

### 3. Bridge your API to MCP

` + "```bash" + `
# Generate MCP Tool CRDs from the example OpenAPI spec
stoactl bridge example-api.yaml --namespace default --output ./tools/

# Or use your own spec
stoactl bridge your-api.yaml --namespace default --output ./tools/
` + "```" + `

### 4. Register tools with the gateway

` + "```bash" + `
# Apply each generated tool
for f in tools/*.yaml; do stoactl apply -f "$f"; done

# Verify tools are registered
stoactl get tools
` + "```" + `

### 5. Test via MCP

` + "```bash" + `
# List available tools
curl -s http://localhost:{{.Port}}/mcp/v1/tools | jq .

# Invoke a tool
curl -s http://localhost:{{.Port}}/mcp/v1/tools/invoke \
  -H "Content-Type: application/json" \
  -d '{"name": "list-items", "arguments": {"limit": 5}}' | jq .
` + "```" + `

## Project Structure

` + "```" + `
{{.ProjectName}}/
├── docker-compose.yml   # Gateway + echo backend
├── stoa.yaml            # Gateway configuration
├── echo-nginx.conf      # Echo backend (returns static JSON)
├── example-api.yaml     # Example OpenAPI spec for bridge
├── tools/               # Generated Tool CRDs (after bridge)
└── README.md            # This file
` + "```" + `

## Documentation

- [STOA Docs](https://docs.gostoa.dev)
- [Quick Start Guide](https://docs.gostoa.dev/docs/guides/quick-start)
- [CLI Reference](https://docs.gostoa.dev/docs/reference/cli)
`
